name: generate PageSpeed Insights report

on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:

jobs:
  create-psi-report-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
        with:
          repository: ryota0222/portfolio-v5
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ env.DEVOPS_DIR }}
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: "x64"
      - name: pip setting
        run: |
          python -m pip install --upgrade pip
          pip install datetime
          pip install requests
      - name: run python
        run: |
          python ${{ env.DEVOPS_DIR }}/src/scripts/pageSpeedInsight.pyã€€
          mv ${{ env.DEVOPS_DIR }}/src/scripts/*.json public/data/psi/
      - name: commit files
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'generate PageSpeed Insights report of today'
          git push origin main
